title: Huasheng Huang
subtitle: PhD candidate at UvA
description: Website and portfolio of Huasheng Huang, PhD candidate.

author: Huasheng Huang
email: buxushuang@gmail.com
avatar: assets/images/avatar.jpg

baseurl: ""
url: "https://huashenghuang.github.io"

# Social settings
facebook_url: https://www.facebook.com/chris.bobbe
github_url: https://github.com/chrisbobbe
linkedin_url: https://www.linkedin.com/in/chrisbobbe1995/
twitter_url: https://twitter.com/chrisbobbe

# SEO settiongs
google_analytics: UA-112211352-1

# Build settings
remote_theme: chrisbobbe/jekyll-theme-prologue
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Necessary for Prologue theme:
collections: [sections]
